name: Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306
        env:
          MYSQL_DATABASE: trinity
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    strategy:
      matrix:
        php:
          - "8.1"

    steps:
      - uses: actions/checkout@v2

      - name: Verify MySQL connection
        env:
          PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done

      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.github', '.env');"

      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "locked"
          composer-options: "--prefer-dist --no-cache --ignore-platform-reqs"

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Configure matchers
        uses: mheap/phpunit-matcher-action@v1

      - name: Run Tests
        env:
          DB_PORT: ${{ job.services.mysql.ports['3306'] }}
        run: ./vendor/bin/phpunit --colors=always
